[2025-02-14T11:51:22.244+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T11:51:22.261+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_all_snowflake_tables.proceed_with_next_task manual__2025-02-14T11:51:13.076891+00:00 [queued]>
[2025-02-14T11:51:22.270+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_all_snowflake_tables.proceed_with_next_task manual__2025-02-14T11:51:13.076891+00:00 [queued]>
[2025-02-14T11:51:22.270+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-14T11:51:22.281+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): proceed_with_next_task> on 2025-02-14 11:51:13.076891+00:00
[2025-02-14T11:51:22.288+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=205) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T11:51:22.290+0000] {standard_task_runner.py:72} INFO - Started process 207 to run task
[2025-02-14T11:51:22.289+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'check_all_snowflake_tables', 'proceed_with_next_task', 'manual__2025-02-14T11:51:13.076891+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/snow.py', '--cfg-path', '/tmp/tmp5gxq5lh2']
[2025-02-14T11:51:22.292+0000] {standard_task_runner.py:105} INFO - Job 104: Subtask proceed_with_next_task
[2025-02-14T11:51:22.333+0000] {task_command.py:467} INFO - Running <TaskInstance: check_all_snowflake_tables.proceed_with_next_task manual__2025-02-14T11:51:13.076891+00:00 [running]> on host 94016f1f831c
[2025-02-14T11:51:22.412+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='check_all_snowflake_tables' AIRFLOW_CTX_TASK_ID='proceed_with_next_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T11:51:13.076891+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T11:51:13.076891+00:00'
[2025-02-14T11:51:22.414+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-14T11:51:22.427+0000] {logging_mixin.py:190} INFO - âœ… All required tables exist. Proceeding with the next task...
[2025-02-14T11:51:22.428+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-14T11:51:22.437+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-14T11:51:22.438+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=check_all_snowflake_tables, task_id=proceed_with_next_task, run_id=manual__2025-02-14T11:51:13.076891+00:00, execution_date=20250214T115113, start_date=20250214T115122, end_date=20250214T115122
[2025-02-14T11:51:22.465+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T11:51:22.487+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T11:51:22.490+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
